language: node_js
node_js:
  - '16'
before_script:
  - yarn build
before_deploy:
  - git config --local user.name "metowolf"
  - git config --local user.email "i@i-meto.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: public/*
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
